spring.application.name=account-service

# Conexion a Postgres (contenedor Docker que ya tienes corriendo)
spring.datasource.url=jdbc:postgresql://localhost:5432/banking
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT (los agregamos ya para cuando integremos seguridad)
app.jwt.secret=qAVUvzsO6MdtL7w5JjKQ4lZv3P6g6xVFryYSG9r9HcAviiuZL9wzA6vduZt8Vf4Dbv9Deh73dm7wXinzMtLZmw==
app.jwt.expiration-ms=3600000
app.auth.username=admin
app.auth.password=admin123

server.port=8080